---
# Base URL for tailscale repository
tailscale_package_url: https://pkgs.tailscale.com

# Tailscale branch to install
tailscale_branch: stable

# Optionally, generate TLS certificates managed by tailscale
tailscale_generate_certs: no

# DNS name for generating TLS certificates
# Has to be choosen from https://login.tailscale.com/admin/settings/features (HTTPS section)
# tailscale_domain: ""
