galaxy_info:
  author: Federico Antoniazzi
  description: Ansible role to install tailscale in my homelab
  # company: your company (optional)

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: MIT

  min_ansible_version: 2.1

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
  - name: Debian
    versions:
      - 11
  - name: Raspbian
    versions:
      - 11

  galaxy_tags:
    - homelab
    - vpn
    - tailscale

dependencies: []
