---
- name: Gather service facts
  become: yes
  service_facts:

- name: Disable wpa supplicant
  become: yes
  systemd:
    name: wpa_supplicant
    enabled: no
    state: stopped
  when: "'wpa_supplicant.service' in services"
