---
- name: Gather package facts
  become: yes
  package_facts:
    manager: auto

- name: Gather service facts
  become: yes
  service_facts:

- name: Uninstall snapd if installed
  become: yes
  block:
    - name: Purge snap and snapd
      apt:
        pkg:
          - snap
          - snapd
        state: absent
        purge: yes
    - name: Disable snapd services
      systemd:
        name: snapd
        state: stopped
        enabled: no
      when: "'snapd.service' in services"
    - name: Remove user snap folder
      file:
        path: "/home/{{ ansible_user_id }}/snap"
        state: absent
    - name: Remove system snap folders
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/snap"
        - "/var/snap"
        - "/var/lib/snapd"
        - "/var/cache/snapd"
        - "/usr/lib/snapd"
  when: "'snap' in ansible_facts.packages or 'snapd' in ansible_facts.packages"
