---
- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Upgrade all packages
  become: yes
  apt:
    name: "*"
    state: "latest"

- name: Removing unused packages
  become: yes
  apt:
    autoremove: yes
